package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Costumer;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface CostumerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COSTUMER
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    int deleteByPrimaryKey(Integer personalcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COSTUMER
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    int insert(Costumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COSTUMER
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    Costumer selectByPrimaryKey(Integer personalcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COSTUMER
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    List<Costumer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COSTUMER
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    int updateByPrimaryKey(Costumer record);
}