package lt.vu.mybatis.model;

public class Manufacturer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MANUFACTURER.ID
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MANUFACTURER.DESCRIPTION
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MANUFACTURER.LOCATION
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MANUFACTURER.NAME
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MANUFACTURER.ID
     *
     * @return the value of PUBLIC.MANUFACTURER.ID
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MANUFACTURER.ID
     *
     * @param id the value for PUBLIC.MANUFACTURER.ID
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MANUFACTURER.DESCRIPTION
     *
     * @return the value of PUBLIC.MANUFACTURER.DESCRIPTION
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MANUFACTURER.DESCRIPTION
     *
     * @param description the value for PUBLIC.MANUFACTURER.DESCRIPTION
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MANUFACTURER.LOCATION
     *
     * @return the value of PUBLIC.MANUFACTURER.LOCATION
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MANUFACTURER.LOCATION
     *
     * @param location the value for PUBLIC.MANUFACTURER.LOCATION
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MANUFACTURER.NAME
     *
     * @return the value of PUBLIC.MANUFACTURER.NAME
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MANUFACTURER.NAME
     *
     * @param name the value for PUBLIC.MANUFACTURER.NAME
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    public void setName(String name) {
        this.name = name;
    }
}