package lt.vu.mybatis.model;

import java.util.Date;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ORDERS.ID
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ORDERS.ADDRESS
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ORDERS.DELIVERY_DATE
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    private Date deliveryDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ORDERS.COSTUMER_FK
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    private Integer costumerFk;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ORDERS.ID
     *
     * @return the value of PUBLIC.ORDERS.ID
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ORDERS.ID
     *
     * @param id the value for PUBLIC.ORDERS.ID
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ORDERS.ADDRESS
     *
     * @return the value of PUBLIC.ORDERS.ADDRESS
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ORDERS.ADDRESS
     *
     * @param address the value for PUBLIC.ORDERS.ADDRESS
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ORDERS.DELIVERY_DATE
     *
     * @return the value of PUBLIC.ORDERS.DELIVERY_DATE
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    public Date getDeliveryDate() {
        return deliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ORDERS.DELIVERY_DATE
     *
     * @param deliveryDate the value for PUBLIC.ORDERS.DELIVERY_DATE
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ORDERS.COSTUMER_FK
     *
     * @return the value of PUBLIC.ORDERS.COSTUMER_FK
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    public Integer getCostumerFk() {
        return costumerFk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ORDERS.COSTUMER_FK
     *
     * @param costumerFk the value for PUBLIC.ORDERS.COSTUMER_FK
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    public void setCostumerFk(Integer costumerFk) {
        this.costumerFk = costumerFk;
    }
}