package lt.vu.mybatis.model;

import java.math.BigDecimal;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.BARCODE
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    private Integer barcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.COST
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    private BigDecimal cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.DESCRIPTION
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.TITLE
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.BARCODE
     *
     * @return the value of PUBLIC.PRODUCT.BARCODE
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    public Integer getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.BARCODE
     *
     * @param barcode the value for PUBLIC.PRODUCT.BARCODE
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    public void setBarcode(Integer barcode) {
        this.barcode = barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.COST
     *
     * @return the value of PUBLIC.PRODUCT.COST
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    public BigDecimal getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.COST
     *
     * @param cost the value for PUBLIC.PRODUCT.COST
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.DESCRIPTION
     *
     * @return the value of PUBLIC.PRODUCT.DESCRIPTION
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.DESCRIPTION
     *
     * @param description the value for PUBLIC.PRODUCT.DESCRIPTION
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.TITLE
     *
     * @return the value of PUBLIC.PRODUCT.TITLE
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.TITLE
     *
     * @param title the value for PUBLIC.PRODUCT.TITLE
     *
     * @mbg.generated Mon Apr 02 17:00:15 EEST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }
}